### ISSUE TITLE
Include version number in module names

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#163]
**QuitarHero at 1/16/2020 5:19:15 AM +00:00**
> > **Suggestion:**
> Add version number to module names.
> 
> **Conversation Reference:**
> https://discordapp.com/channels/531175899588984842/534492173362528287/667234287669477397

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/667236404895547404

**Comment by dlamkins** [comment]
This is kind of outside of the scope of the project and just comes down to whatever naming convention developers use when sharing their modules.  Outside of that, it can become difficult to upgrade your modules in place as it is if the names are different as you'll have to manually remove the old versions while importing the new ones since they won't just replace them when copied to the modules directory.

This will all be unnecessary anyways once module management from the bhud-pkgs repo is supported.
