### ISSUE TITLE
Provide better DPI scaling support.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#179]
**Shen at 3/27/2020 11:31:27 PM +00:00**
> hmm im just wondering does blishhud scales when 'dpi scaling' is off? on mine it doesnt really ( i use a 2560 x 1440 monitor btw)

REF: https://discordapp.com/channels/531175899588984842/531175900100952087/693240804977672203

**Comment by entrhopi** [comment]
![image](https://user-images.githubusercontent.com/17331922/128494831-29ed4fa8-a309-4c49-94e1-f6410a48cee4.png)

2560 x 1440 on 150% DPI scaling, while it is turned on in the game client.
The Blish window isn't scaled too compared to the native ones.

Since this is a setting that is to be toggled in the game we should provide a similar toggle for Blish too.
