### ISSUE TITLE
Process handle not refreshed and becomes stale

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#260]
**Greaka at 6/25/2020 6:24:12 AM +00:00**
> okay, regarding <#534492012263636992>:
> the main window had a faulty handle, i assumed that bhud catched the login handle and didnt update when the game started
> so my temporary fix was changing `public IntPtr Gw2WindowHandle { get; private set; }` to
> ```cs
>         public IntPtr Gw2WindowHandle 
>         {
>             get
>             {
>                 this.Gw2Process.Refresh();
>                 return this.Gw2Process.MainWindowHandle;
>             }
>         }
> ```
>
> it refreshes the cached process object before accessing the windowhandle
> 
> before merging this into the dev branch, we should proabably think about a better way as there are 8 references, sometimes in controls that use this handle

**Source discussion from the #💢help channel:** https://discordapp.com/channels/531175899588984842/534492012263636992/725566715466874892

**Logs:**
[blishhud.20200624-211059.log](https://github.com/blish-hud/Blish-HUD/files/4829546/blishhud.20200624-211059.log)

> 21:23:45.7555|WARN|Blish_HUD.WindowUtil|GetClientRect failed with error code 1400.

REF: https://discordapp.com/channels/531175899588984842/536970543736291346/725597194371203092

**Comment by dlamkins** [comment]
> before merging this into the dev branch, we should proabably think about a better way as there are 8 references, sometimes in controls that use this handle

To that end, @greaka Is `.Refresh()` a slow call?

![image](https://user-images.githubusercontent.com/1950594/85669834-3c35ee00-b68e-11ea-9ac6-f66b2fae2192.png)

The majority of these uses that would be more frequent are from the classes in place to allow sending input to the game.  For obvious reasons that shouldn't be something that happens rapidly, anyways, so depending on how quick it is, it may not affect things all that much.

Alternatively, since this seems to rarely be an issue, we could avoid refreshing the process unless we encounter the issue.

This is where it triggers the exception shown in the log: https://github.com/blish-hud/Blish-HUD/blob/45282bd19dcba8c1d571c333d394590d2020db13/Blish%20HUD/_Utils/WindowUtil.cs#L152-L160

Which is called from within the `GameIntegrationService`'s update loop: https://github.com/blish-hud/Blish-HUD/blob/45282bd19dcba8c1d571c333d394590d2020db13/Blish%20HUD/GameServices/GameIntegrationService.cs#L334-L346

If the call returns `Errored` we could refresh the process and see if it is still running first instead of just resetting it back to `null` like we are currently.

We could also expand the `OverlayUpdateResponse` enum to include more explicit error responses (for instance `ErroredGetClientRect1400`) so that we can handle them appropriately when they are encountered.

**Comment by greaka** [comment]
It is not slow enough to be a major concern for us. For now, it would probably be fine if we put it in the update loop. I just want to avoid refreshing it multiple times per update. The Refresh on error sounds good too.
