### ISSUE TITLE
Consider adding shortcut to settings dir in the install folder. 

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/Blish-HUD#493]

**Comment by entrhopi** [comment]
I don't think that this is really feasible since we have portable mode and it would have to be dynamic. i.e. when there are multiple accounts used on the machine with a single central Blish installation.

And we have #553 now, so it's pretty easy for the user to get to the current settings folder during runtime.

**Comment by dlamkins** [comment]
I think that's fair.  We'll go ahead and close.
