### ISSUE TITLE
move icon when on chinese client

### ISSUE THREAD

**Issue by greaka** [blish-hud/Blish-HUD#50]
move the bhud icon one slot to the right when we detect a chinese client, as they have an additional icon on the left upper corner icon bar

REF: https://discordapp.com/channels/531175899588984842/534492012263636992/600677943093493760

**Comment by dlamkins** [comment]
We can base this off of the localization, which could be convenient.  

It might be good to expose some advance features that allow for manually setting the number of icons ours are offset by to better future proof things, too.

**Comment by greaka** [comment]
thought about that as well but what if people prefer english over chinese?
i prefer english over german for example

**Comment by dlamkins** [comment]
That's what I figured would be a good use case for "It might be good to expose some advance features that allow for manually setting the number of icons ours are offset by to better future proof things, too."

It may be easier to detect the client specifically, though.  It's been a while since it was last discussed, so I forget: did we find a way to detect the Chinese client specifically?  If we can detect the chinese client, then that would probably be a better method.

**Comment by greaka** [comment]
mumble link almost certainly should contain chinese characters ^^

**Comment by dlamkins** [comment]
I suppose the Identity -> name likely would.  Not sure there is any guarantee on that, though.  I'll ask.

**Comment by dlamkins** [comment]
Had some discussion about this, here: https://discordapp.com/channels/384735285197537290/384740380014280714/600730077688365087

Seems like a good option would be to use the Mumble connection to get the build at launch and compare it to the build endpoint's response.  The web API will return the non-chinese build number and it should not match the build number returned by the Mumble connection.

**Comment by dlamkins** [comment]
REF: https://discordapp.com/channels/384735285197537290/384735523521953792/600743022790967306

We'll compare the build number provided by the MumbleLink API with the build number at: http://assetcdn.111.cgw2.com/latest/111 which represents the current Chinese build number.

**Comment by dlamkins** [comment]
Resolved in #106
