### ISSUE TITLE
Tracking issue for arcdps common

### ISSUE THREAD

**Issue by greaka** [blish-hud/Blish-HUD#58]
Depending on the feedback thats coming in the discord, I will add some common Properties for access to everyone - like if and which mount is currently equipped
I just dont know yet what the best option would be to just conditionally listen to those events

#40 
ref: https://discordapp.com/channels/531175899588984842/534490472224391169/598194017787969537

**Comment by dlamkins** [comment]
This is difficult.  For some things, such as the buffs that you mention, it may be best just to track those regardless if something is checking for it or not.

If you have anything that would be event based, you can check if anything is subscribed by checking the value of the event object.

```cs
public event EventHandler Foo;
 
public void CheckFoo() {
    if (this.Foo == null) {
        // Nothing is subscribed, so we can skip whatever processing this is.
    } else {
        // Something is listening and so we'll have to start calculating whatever this is.
    }
}
```

What other things do you think will be available through this service that we may need to turn on or off depending on if something needs it or not?

**Comment by greaka** [comment]
Whatever you like
The question is more: do we want to just activate all at once or do we want fine control over what is monitored and what isn’t?

**Comment by dlamkins** [comment]
I think that's hard without knowing what the performance impact of having it all enabled looks like.  I don't want to get into premature optimization territory, but I also recognize that this service is throwing around a lot of data in memory and so I don't want to underestimate it either.

If it's only a couple of items now, I'd say that we should go ahead and have it enabled upfront, but if we encounter issues down the road, I think we can switch it to have endpoints only run when being listened to as a non-breaking change to the API the service exposes.  Most modules are enabled first thing and can make this known so that things like buff states aren't lost.  Missing previously set buff states may just have to be a sacrifice that is made for modules that are enabled later in the life cycle.

Tonight I can do some profiling on it if you can give me some details on how the mount buff stuff would/should look like.  Perhaps you can link the ArcDPS documentation here or DM me with it so that I can poke at it to emulate some foreseeable use cases and check what the CPU profiler says with and without those endpoints running.  You've got ReSharper, too, I believe, so if you wanted to profile it, I'm up for that as well.

**Comment by greaka** [comment]
alright, ty :)

i think it shouldnt be too bad, because the worst thing we can do is O(n). I just have to remind myself to make everything either thread safe or only update on gametick

you can find everything you need on the readme for the dll (thanks for reminding me that i have to test the latest changes before i make a new release ^^)
if you want to test them too, hit me up and i send you a dll 😃
