### ISSUE TITLE
Delete Modul Settings when deleting Module

### ISSUE THREAD

**Issue by ghost** [blish-hud/Blish-HUD#586]
Hi,

currently module settings are retained upon deletion of a module. Since most modules don't have a reset configuration Option there's no way to fix a falsely set of options that you can't undo in the UI. 

E.g. if you hide an event in the event module by accident there's currently no option except for a reinstall to get that event back.

Best regards,
Valentin

**Comment by dlamkins** [comment]
Hey @valentin-ok, two questions to make sure we're on the same page:

1. Could you confirm if this is the Events and Metas module or the Events table module?  I'm unsure with the latter, but the prior does not stop you from re-enabling any events you wish to see again.
2. In the cog menu of your modules (next to the enable button), there is an option to reset the modules settings.  Could you please try this and let us know if it does what you're looking to do?

We don't have any plans on fully deleting settings when a module is deleted since modules can be deleted both through the UI and manually from the modules folder, but in any case, we want to retain any configuration the user has for if they choose to restore the module in the future.

**Comment by ghost** [comment]
That did it, thank you. It seems I got confused by the UI. Thank you.
