### ISSUE TITLE
Discussion: Rework fallible Contexts for better error handling

### ISSUE THREAD

**Issue by greaka** [blish-hud/Blish-HUD#62]
this is more of a request for discussion:
theres not really a way to predict exact timings of annual events
so what would you say if the marker module had an optional(!) service that it would call thats gets timings for events. we would have to manually insert those events (so every 2 months putting in some times), the festival service (because maybe some other module could benefit from it?) would either expose if it can reach the service at all (kinda like arcdps service currently) or default to every event active when the service is unreachable
that way we could expose markers to hide depending on festivals

![example image](https://cdn.discordapp.com/attachments/534490472224391169/601637629221666856/unknown.png)

ref: https://discordapp.com/channels/531175899588984842/534490472224391169/601637629221666857

**Comment by dlamkins** [comment]
It may be worth putting together a "ContextService". Something that tries to piece together the available information to give an educated guess on the clients current state, etc. That could even be where detecting mounts from the ArcDps service could potentially live.

**Comment by greaka** [comment]
I dont know, i think its good that we distinguish between stuff that needs 3rd party (read: my arcdps plugin) and the rest

**Comment by dlamkins** [comment]
Oh, that's a good point.

I'm wondering now if we would benefit from restructuring things a little bit to have `Context`s that target specific parts of the game and each one uses information compiled from potentially multiple sources to try and describe the current state of things.

Then we could move some of the services in as contexts, instead.  `PlayerService` would be a good candidate for this since some data would be from `GwMumbleService` and some from `Gw2ApiService`, potentially.  It would become the `PlayerContext` or something like that.  Contexts could consume information provided by services to try and describe their current state and maybe indicate their "certainty" somehow.

It would be similar to how currently the `CameraService` basically acts as a proxy on top of the `Gw2MumbleService` despite the camera information technically being provided by the `Gw2MumbleService`.

Handling "certainty" seems like it would be the fairly difficult part.  For some things, it could simply be event based like "PlayerMounted" or "PlayerUnmounted," which would assert with full certainty what happened since they would require a known state change to occur in order to happen.

Alternatively, module writers could make sure that their module degrades gracefully if certain information is not defined or provided.

**Comment by greaka** [comment]
I like the idea of having an abstract base context, that has a field for `isPopulated` or something and maybe some other stuff
That way modules could check if they can rely on those information

**Comment by dlamkins** [comment]
We could have all of the properties they expose be methods in a pattern similar to `TryGet____()` which would return a `bool` indicating if it is populated or not.  So an example could get:

`bool GetCurrentMountIfPopulated(out var currentMount);`

Potential alternative naming patterns (using `CurrentMount` as an example):
`bool GetCurrentMountIfAvailable(out var currentMount);`
`bool IfAvailableGetCurrentMount(out var currentMount);`
`bool IfPopulatedGetCurrentMount(out var currentMount);`
`bool GetCurrentMountIfKnown(out var currentMount);`
`bool IfKnownGetCurrentMount(out var currentMount);`

I tend to prefer that option over having a separate `isPopulated`, but I do like the idea of also having a `IsCurrentMountPopulated`.

Examples with other contexts:

**PlayerContext**
`bool GetPositionIfPopulated(out var position)`
`bool GetNameIfAvailable(out string name)`
etc.

**FestivalContext**
`bool GetCurrentFestivalIfKnown(out Gw2Festival festival)`
`bool GetCurrentFestivalIfAvailable(out Gw2Festival festival)`
etc.

Would something like that sound good to you on the contexts?  If so, which pattern do you prefer (or do you have any alternatives you would like to propose)?  I could also see having *maybe* two patterns based on verbage (but strictly defined so that it's not ambiguous what should use which pattern), but I imagine I'm getting a little bit ahead of myself.

**Comment by greaka** [comment]
@nickcode122 whats your take on this?

i think its an interesting approach, and it looks like its gonna be a lot of breaking changes
On the other side, we could seperate by concern in contrast to by technology without loosing context

my proposed name would be `TryGetCurrentMount`, with comments what its depending on

**Comment by nickcode122** [comment]
@greaka Could you elaborate on what you mean by technology here?
> seperate by concern in contrast to by technology

I do like the idea @dlamkins is proposing regarding contexts. I do think I like the way TryGetCurrentMount sounds, but naming pattern so long as it's descriptive isn't super important to me.

**Comment by greaka** [comment]
Some information is requested from the api, from the mumble link or from the arcdps service

So those technologies could always fail on their own and it would be kind of hard to recognize why only some of the `TryGetFoo` stuff failed

**Comment by dlamkins** [comment]
> So those technologies could always fail on their own and it would be kind of hard to recognize why only some of the TryGetFoo stuff failed


@greaka That's a good point that I hadn't considered.

How about something more robust, then?

Consider the following structure:

```cs
    public enum ContextStatus {
        Available,
        Unavailable,
        Failed
    }

    public sealed class ContextResult<T> {
        public T      Value  { get; }
        public string Status { get; }

        public ContextResult(T value, string status) {
            this.Value  = value;
            this.Status = status;
        }
    }
```

Then the following example context (static for the sake of the example - they'd likely be better suited as singletons, like the `GameService`s):

```cs
public enum ClientType {
    Unknown,
    Standard,
    Chinese
}

public static class ClientContext {

    public static ContextStatus TryGetVersion(out ContextResult<ClientType> contextResult) {
        contextResult = new ContextResult<ClientType>(ClientType.Chinese, "Success");

        return ContextStatus.Available;
    }

}
```

Then, for the above context, we can do:

```cs
private void Test() {
    switch (ClientContext.TryGetVersion(out var contextResult)) {
        case ContextStatus.Available:
            // Do something with the information since it's available
            break;

        case ContextStatus.Failed:
            // Display error in UI to indicate there was a problem and why
            Logger.Warn("Failed to get info from ClientType context: {contextStatus}", contextResult.Status);
            break;

        case ContextStatus.Unavailable:
            // Do something graceful if context is unavailable
            break;
    }
}
```

This lets us consume from the context if it's available or not and still see if we could or could not get it and why.

If we wanted to make things even easier, we could also support implicit cast on the `ContextResponse` with:
```cs
public static implicit operator T(ContextResult<T> contextResult) => contextResult.Value;
```

So that if it returns with `ContextStatus.Available`, folks can start working with the resulting value without needing to deal with the intermediary type.

**Comment by dlamkins** [comment]
FYI - I started testing this out some in a local branch and an currently seeing good results.  I'll put in a draft PR when I get up a bit later today so that it can be seen by others.  Definitely let me know your thoughts on what I've proposed, though.

I just got excited and started working on it, is all, hoping that others like it as well.  I was working on #50 and realized that this would likely be a good base to build off of for this (`ClientTypeContext` + `CdnInfoContext`).

I can have fairly easy support for other modules adding their own contexts in, if they would like, and then Context instances can be acquired via:

```cs
GameService.Contexts.GetContext<FooContext>();
```

Which would look like:

```cs
GameService.Contexts.GetContext<ClientTypeContext>().TryGetClientType(out ContextResult<ClientType> contextResult);
```

This would also be a good home for:

```cs
GameService.Contexts.GetContext<ClientTypeContext>().TryGetExecutablePath(out ContextResult<string> contextResult);
```

Instead of having the execution path get detected in the GameIntegrationService, it could be in that context and help keep things a little cleaner.

**Comment by greaka** [comment]
I like the general idea, but im not sure how I feel about having a switch after every function call

In addition I would like to know how bad this `GetContext<T>` is for the update loop, if you have a benchmark, throw it at us 😄 

Otherwise this is a great idea on how to provide an interface between modules!

Is it possible to get the `?` operator in there as well?
Which would result in:

```cs
var clientType = GameService.Contexts.GetContext<ClientTypeContext>()?.GetClientType();
```

So the context is the general availability of the context and if theres something that can fail in the context, then it will provide its own way (maybe even the same) of handling that. This could make the use of those contexts easier and we wouldnt have to type a switch every time.


To come back to the performance, if we have to hold references to the context, for performance reasons, then we need to ensure that the context doesnt expire (which is kind of impossible with modules providing a context).
One solution would be to have an `Invalidate()` function that has to be called from every context provider for its own contexts.
The other approach would be to request a context whenever needed, but I would like to wait for some numbers here.

**Comment by dlamkins** [comment]
> I like the general idea, but im not sure how I feel about having a switch after every function call

Understandable.  I think it's quite verbose.  Unless you need to branch your logic very specifically, you can probably just check for success and then pass failures to a UI view or logging call to be displayed or logged.

```cs
if (_cdnInfoContext.TryGetStandardCdnInfo(out var chineseCdnContextResult) == ContextStatus.Available) {
    DoSomethingWithBuildNumber(chineseCdnContextResult.Value.BuildNumber);
}
```

> Is it possible to get the `?` operator in there as well?

Certainly can!  I'll include it in the benchmark.

> In addition I would like to know how bad this GetContext<T> is for the update loop, if you have a benchmark, throw it at us 😄

It was not as bad as I expected!

``` ini
BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17134.950 (1803/April2018Update/Redstone4)
Intel Core i7-4790K CPU 4.00GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
  [Host]     : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3416.0
  DefaultJob : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3416.0
```
|                       Method |      Mean |     Error |    StdDev | Rank |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------- |----------:|----------:|----------:|-----:|-------:|------:|------:|----------:|
|         WithContextGetByType | 33.938 ns | 0.6987 ns | 1.4272 ns |    2 | 0.0076 |     - |     - |      32 B |
| WithContextGetByTypeNullable | 34.674 ns | 0.7690 ns | 1.4999 ns |    2 | 0.0076 |     - |     - |      32 B |
|            WithCachedContext |  6.440 ns | 0.1600 ns | 0.4215 ns |    1 | 0.0076 |     - |     - |      32 B |

So, if there was a context that you needed to call to many times per loop, it would be beneficial to cache the reference.  I don't expect most contexts to have a reason to be called that frequently, though, so perhaps we should list out any ideas for contexts we have to make sure we better account for any oddities.

> So the context is the general availability of the context and if theres something that can fail in the context, then it will provide its own way (maybe even the same) of handling that. This could make the use of those contexts easier and we wouldnt have to type a switch every time.

I suppose the benefit of the original idea was that different endpoints within the same context could be or not be available.  For instance `TryGetClientType` might fail due to one of the dependencies being unavailable (CDN endpoint is unavailable, mumble Link API not available, etc.), but `TryGetClientExecutablePath` could still succeed.

Could you provide some examples on how "then it will provide its own way (maybe even the same) of handling that" could work?  A non-standard way could be a bit more annoying to deal with, but I do get that it'd be nice to have the call return the result directly.  I think with declaration expressions allowing us to inline the output, it ends up being nearly the same result and gives us the added benefit of letting us stick the call into an "if" or "switch" to handle the result status.  Could you provide an example implementation of your thoughts, perhaps, that I could see?

> we need to ensure that the context doesnt expire (which is kind of impossible with modules providing a context).

That's a very good point and I think your idea is spot on.  Since the contexts will need to get removed from the Contexts service anyways, we could have `UnregisterContext()` remove it from the lookup dictionary *and* also call `Invalidate()` on the context.  Invalidated Contexts could then just immediately return from calls with a different status such as `ContextStatus.Invalid` depending on how we decide how to handle returning that information.

> The other approach would be to request a context whenever needed, but I would like to wait for some numbers here.

Yeah, based on the numbers I'm seeing, I think in most cases it'd be be fine to use `GetService` each time, but if there was something you wanted to call very frequently, it'd be important to cache the reference.

----

Previously I was thinking that `PlayerService` and `CameraService` would be good candidates for context service, but with further thought, I don't think that they would be.  That may make you feel better about the timings as I can't think of any contexts that would need to get called too frequently.

**Comment by dlamkins** [comment]
@greaka 

#106 is my example implementation PR.  

I have not implemented the `UnregisterContext()` call yet, but `Context`s do have `Unload()` on them which is what I think can be used for those `Invalidate()` calls (so just a name change since `Control`s already have `Invalidate()` and I don't want to confuse the meaning too much as they are used differently).

`Context`s also have a bool `Ready` property which indicates if the `Context` has finished loading what it needed from its dependencies.  Also fires an event when it is ready is something wants to use it once it's ready.

Interested to hear your feedback!

**Comment by greaka** [comment]
I like what I see so far. Apart from some missing features 😄

**Comment by dlamkins** [comment]
@greaka Glad to hear it!  Just to make sure I take everything into account when I go to start finalizing some of the Context stuff here tonight, can you remind me what those missing features were?  I know the unregistering / unloading of contexts is on that list as well.  Was there anything else specific to contexts that you want me to be aware of / remind me of?  🙂

**Comment by greaka** [comment]
just the unloading stuff and invalidating it. maybe you can make the `ready` bool an enum or extend the availability enum to include `expired` or something like that. I wish we had [tagged unions](https://en.wikipedia.org/wiki/Tagged_union) to make that all nicer to work with

**Comment by greaka** [comment]
heh, I see you already thought similarly about that ^^

https://github.com/blish-hud/Blish-HUD/pull/106/files/5db0ce8b2cd83c67f25b22309ba64f40e1e0877a..e91b4e6081ef57b08d032aa44ae75251671a7c57#diff-a381d608706f9811686c6f622010851cR13-R17

**Comment by greaka** [comment]
I dont know if telling modules if its not ready yet or not ready anymore might be important. They could handle refreshing differently

**Comment by dlamkins** [comment]
@greaka is that something like this? https://stackoverflow.com/a/3151901

I'm going to look closer at the availability types and see if I can't make them a little clearer in name and description. I feel like they aren't as clear cut as they should be. I think replacing `Ready` with an enum and calling it `ContextState` would also help give better visibility for other states like loading (so we can call again later), expired (so we can drop our reference), etc. would be a good idea like you mentioned. I played with it some where loading was known privately to the `CdnInfoContext`, but I think all Contexts could probably benefit.

**Comment by greaka** [comment]
have a look at rust enums :)

**Comment by greaka** [comment]
I am closing this now, since the new context system is now implemented and doesn't need any discussion in here anymore.

I've opened a new issue about the festival service in #123
