### ISSUE TITLE
BlishHud makes Black Lion Trading Company extremely slow

### ISSUE THREAD

**Issue by Huxwells** [blish-hud/Blish-HUD#727]
Good morning! I have been experiencing some lag with the Black Lion Trading Company since about a week or two (sorry, don't remember the exact date). Gem store, currency exchange and trading post are all incredibly slow, rendering them effectively unusable. Recently, I accidentally bought an item three times and ended up spending 21 instead of 7 gold...

After turning everything off in the background (browsers, ArcDPS and BlishHud), I've discovered that BlishHud is causing this. With just BlishHud running, it continues to happen.

Any suggestions on how to fix this? Many thanks!

**Comment by dlamkins** [comment]
I've seen many reports of recent slowness issues with the trading post over the last couple of weeks by non-Blish HUD users. A recent game update updated the platform used to run it and some of the other in-game UI.

Your issues timing seems to correlate with this so I believe it is coincidence since I can't replicate the slowness issue you're referencing (Blish HUD also didn't injected into the game, so it would have direct way to cause this).

Could you please provide your in-game graphics and Blish HUd settings via screenshot and confirm preferably with video or screenshots that you can reliably cause the issue by running Blish HUD and show the difference with it off?

**Comment by Huxwells** [comment]
Hi there! For my graphics, check the below two images. FYI, I'm playing on a new desktop, only "older piece" is my RTX 2060 super graphics card (2-3 years old). All other elements are brand new.
![image](https://user-images.githubusercontent.com/109653420/182690057-fd231ad0-c77a-4671-b19f-3c4872d34d2f.png)
![image](https://user-images.githubusercontent.com/109653420/182690368-3acd8488-2b1b-477b-848c-4f113945c8d3.png)

And are these the settings you needed from BlishHud? See the next image!
![image](https://user-images.githubusercontent.com/109653420/182690583-9f8bfc05-031e-48a9-b756-564e390fde6b.png)

Finally, I've also put 3 videos on WeTransfer. I screenrecorded my sessions - unfortunately it does not register overlays, but the BlishHud overlay -is- active in videos 2 & 3. Video's here: https://we.tl/t-UV0yM0ROQe.
Some explanation:
- Video 1: when I start up my computer and GW2 without BlishHud altogether. You can see that the trading post is working perfectly fine.
- Video 2: when I start up BlishHud in the same game session, you can notice that there is some lag developping on the clicking of buttons/hovering/...
- Video 3: when, in the same session, I teleport to a different location (using the teleporter from Mistlock Sanctuary to The Grove), you can notice that the trading post becomes incredibly slow. Unmanageably slow. This is what I am dealing with most of the time, as I'll often have played a lot before even using the trading post.

I have noticed that turning Blishhud back of seems to return the state to that of the second video, but to actually make the trading post smooth again, I need to restart my entire computer.

What are your thoughts? Need any more information?

**Comment by dlamkins** [comment]
Thanks for this information. Since the trading post can slow down with time, it is hard to rule that out still, but the best place to start is going to be re-enabling your Blish HUD frame lock or vsync. You don't want it set to unlimited without vsync it'll use a lot of unecessary graphical resources. 

If your issues appear to persist at all after Blish HUD is closed, it's hard for me to conclude that it's not related to the recent platform changes in GW2, but it is possible that if Blish HUD is unlocked FPS that it exacerbates the issue in the short term.

**Comment by Huxwells** [comment]
This did not fix it, unfortunately... Any other suggestions?

I want to try reinstalling BlishHud, to see if that does anything. How can I do this, and how do I save my settings for both blishhud and its modules?

**Comment by dlamkins** [comment]
Settings are kept under your documents.  There's really no such thing as re-installing Blish HUD since it doesn't install.  If you want to truly revert something, you'd need to wipe the settings.  We don't keep anything else stored on the system.

`\Documents\Guild Wars 2\addons\blishhud`

That said, I do believe this is still a game issue and not actually related to Blish HUD.  We don't inject into the game, so it would be quite difficult for us to impact something so specific.
