### ISSUE TITLE
Events add-on: File and directory names starting with a space causing problems with cloud syncing

### ISSUE THREAD

**Issue by Kurokha** [blish-hud/Blish-HUD#777]
Blish HUD v0.11.7+Branch.tags-v0.11.7.Sha.0c709c76cb502d310f2964dca92ce770e533dae2

I'm using Windows with the Documents directory set up for cloud sync. Blish HUD stores all its data into that directory as well, including the data for the events add-on (Documents\Guild Wars 2\addons\blishhud\events).

Five file and folder names start with a space character, which are causing continued error messages in the syncing process because such names are not supported. I don't know if any other languages besides German are affected. Can these names be corrected or alternatively the directory for Blush HUD data storage be changed?

The following files and folders are affected:

- "Documents\Guild Wars 2\addons\blishhud\events\pois\Die Nebel\1\Welt gegen Welt\ Alpine Grenzlande"
- "Documents\Guild Wars 2\addons\blishhud\events\pois\Die Nebel\1\Welt gegen Welt\ Alpine Grenzlande\ Bastion.txt"
- "Documents\Guild Wars 2\addons\blishhud\events\pois\Die Nebel\1\Welt gegen Welt\ Wüsten-Grenzlande"
- "Documents\Guild Wars 2\addons\blishhud\events\pois\Die Nebel\1\Welt gegen Welt\Ewige Schlachtfelder\ Feste.txt"
- "Documents\Guild Wars 2\addons\blishhud\events\pois\Die Nebel\1\Welt gegen Welt\Ewige Schlachtfelder\ Wegmarke Hügel.txt"

**Comment by dlamkins** [comment]
I've made a note of your issue on the relevant repo for you where this issue has been getting tracked: https://github.com/Tharylia/Blish-HUD-Event-Table/issues/84

Regarding workarounds until it is fixed in the module:

Portable Mode
https://blishhud.com/docs/user/portable-mode

`--settings` launch option
https://blishhud.com/docs/user/launch-options#-s---settings-pathtosettingsdir
