### ISSUE TITLE
Marker `DisplayName` attribute is ignored unless it is provided lowercase in the XML.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#87]
**QuitarHero at 8/13/2019 3:39:31 PM +00:00**
> Using `v0.4.1-dev+172 Sentry` build, while all my markers show up in the menu, it only considers the `name` attribute, and not `DisplayName`

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/610859993251446785

**Comment by dlamkins** [comment]
This was due to the new `PathableAttribute`s assuming everything was being provided lowercase.  The NanoXml reader needs to be updated slightly to ensure all attribute and element names were stored lowercase from the start.  Currently the name is cleaned, but not lowercase'd: https://github.com/blish-hud/Community-Module-Pack/blob/96a565f105ada3ef17df69d338b71a58eb126313/Markers%20and%20Paths%20Module/Library/NanoXml/NanoXmlBase.cs#L54

I have a fix I'll be pushing shortly.
