### ISSUE TITLE
Menus overlapping and blocking option selection

### ISSUE THREAD

**Issue by 1L19** [blish-hud/Blish-HUD#894]
I'm having an issue with menus overlapping to the point where I'm unable to toggle certain checkboxes. I'm on a 17" lappy running 1920x1080 resolution. I have the Blish Overlay Settings>Graphics Settings>Interface Size set to small. DPI setting changes gave no result. I've included two screenshots. The first one is just before the overlap occurs and the second shows the overlap.

![blish blocked menu 3](https://github.com/blish-hud/Blish-HUD/assets/138430981/08f86f10-f651-4436-914d-5b9ae5a28b59)
![blish blocked menu 1](https://github.com/blish-hud/Blish-HUD/assets/138430981/2afcd938-40f3-44ed-b244-f67a2b3f53f1)

Thank you.

**Comment by dlamkins** [comment]
I'm afraid this is not a technical issue for the core application.  Regarding overlapping menus in the pathing module, there is simply a limit to what can fit on screen.  Consider reaching out to the pack maker to simply their menus and reduce the length of their category names so that more can fit.

**Comment by 1L19** [comment]
No problem at all. Thank you very much and I'm sorry to have troubled you. :)
